CREATE TABLE posts (
  -- id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  -- published TINYINT(1) NOT NULL DEFAULT 0
  published BOOLEAN NOT NULL DEFAULT FALSE
);
