version: '3.8'

services:
  mysql:
    image: mysql:8.0.17
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: my_login_app_api
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DATABASE_URL: mysql://${DB_USERNAME}:${DB_PASSWORD}@mysql_db:3306/${DB_NAME}
      RUST_LOG: info
    ports:
      - "8530:8080"
    depends_on:
      - mysql
    env_file:
      - .env

volumes:
  mysql_data:
